version: "3.8"
services:
  builder:
    container_name: builder
    # Build frontend service using Dockerfile.build
    build:
      context: .
      dockerfile: ./docker/Dockerfile.build
      args:
        NODE_VERSION: 20.15.1
        ALPINE_VERSION: 3.14
    # Mount built app to /usr/src in the container
    volumes:
      - build:/usr/src/

  nginx:
    container_name: nginx-proxy
    # Build the nginx service using Dockerfile.stage
    build:
      context: .
      dockerfile: ./docker/Dockerfile.stage
      args:
        NGINX_VERSION: 1.19.6
        PROXY_API_URL: ${PROXY_API_URL:-http://localhost:8080}
        password: ${password}
    # Expose ports 80 and 2222 from the container
    ports:
      - '80:80'
      - '2222:2222'
    # Enable tty and stdin for the container
    stdin_open: true
    tty: true
    # Mount the build volume to /usr/share/nginx/html in the container
    volumes:
      - build:/usr/share/nginx/html
    # Specify dependencies between services
    depends_on:
      - builder

# Define build volume
volumes:
  build: