services:
  builder:
    container_name: builder
    image: ci-dockerfile:build
    args:
      NODE_VERSION: 18.14.2
      ALPINE_VERSION: 3.14
    volumes:
      - build:/usr/src/

  nginx:
    container_name: nginx-proxy
    image: ci-dockerfile:stage
    args:
      NGINX_VERSION: 1.19.6
      PROXY_API_URL: ${PROXY_API_URL:-http://localhost:8080}
      password: ${password}
    # Expose ports 80 and 2222 from the container
    ports:
      - '80:80'
      - '2222:2222'
    # Enable tty and stdin for the container
    stdin_open: true
    tty: true
    # Mount the build volume to /usr/share/nginx/html in the container
    volumes:
      - build:/usr/share/nginx/html
    # Specify dependencies between services
    depends_on:
      - builder

# Define build volume
volumes:
  build:
